[build.environment]
  NPM_FLAGS = "--version"
  NODE_VERSION = "22"

[build]
  publish = "dist"
  command = "npx --yes pnpm@11.15.1 i --store=node_modules/.pnpm-store && npx --yes pnpm@11.15.1 run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
